name: Terraform Validation CI

on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
      - main
    paths-ignore:
      - .github/**

permissions:
  contents: write

jobs:
  validation:
    name: Run Validation Checks 
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:

    - name: Generate GitHub App Token 🪙
      uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
      id: generate-token
      with:
        app_id: ${{ secrets.BRAID_BOT_APP_ID }}
        private_key: ${{ secrets.BRAID_BOT_PRIVATE_KEY }}

    - name: Checkout 🔔
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ steps.generate-token.outputs.token }}

    - name: Install Terraform ⛰️
      uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4

    - name: Run TFLint ✅ 
      uses: terraform-linters/setup-tflint@90f302c255ef959cbfb4bd10581afecdb7ece3e6 # v4
      with:
        tflint_version: latest

  changelog:
    name: Generate Changelog 🗒️
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
      
    steps:

    - name: Generate GitHub App Token 🪙
      uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
      id: generate-token
      with:
        app_id: ${{ secrets.BRAID_BOT_APP_ID }}
        private_key: ${{ secrets.BRAID_BOT_PRIVATE_KEY }}

    - name: Checkout 🔔
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      with:
        token: ${{ steps.generate-token.outputs.token }}

    - name: Conventional Changelog Action 📋
      id: changelog
      uses: TriPSs/conventional-changelog-action@3c4970b6573374889b897403d2f1278c395ea0df # v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        git-user-name: "braid-bot[bot]"
        git-user-email: "169546839+braid-bot[bot]@users.noreply.github.com"
        git-branch: "${{ github.head_ref }}"
        skip-on-empty: "true"
        skip-ci: "false"
        release-count: 10
        version-file: package.yaml
        create-summary: true      